DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
id LONG AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(100) NOT NULL
);
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
id LONG AUTO_INCREMENT  PRIMARY KEY,
isbn VARCHAR(100) NOT NULL,
book_Title VARCHAR(100) NOT NULL,
price DOUBLE NOT NULL,
author_Id Long NOT NULL
);